In [1]:
import torch

In [37]:
import numpy as np

In [8]:
my_tensor = torch.tensor([[1,2,3,5], [2,3,5,6]], dtype=torch.float32, device="mps", requires_grad=True)

In [9]:
my_tensor

tensor([[1., 2., 3., 5.],
        [2., 3., 5., 6.]], device='mps:0', requires_grad=True)

In [10]:
my_tensor.requires_grad

True

In [17]:
x = torch.rand(size=(3,3))

In [18]:
x

tensor([[0.7872, 0.2260, 0.2669],
        [0.5006, 0.3780, 0.0115],
        [0.8301, 0.5176, 0.3074]])

In [20]:
torch.eye(5,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])

In [21]:
torch.arange(start=0, end=5, step=1)

tensor([0, 1, 2, 3, 4])

In [23]:
torch.linspace(start=0.17, end=1, steps=10)

tensor([0.1700, 0.2622, 0.3544, 0.4467, 0.5389, 0.6311, 0.7233, 0.8156, 0.9078,
        1.0000])

In [27]:
torch.empty(size=(1,5)).uniform_(0,1)

tensor([[0.1624, 0.0121, 0.0818, 0.9185, 0.0961]])

In [34]:
tensor = torch.arange(6)

In [31]:
tensor.short()

tensor([0, 1, 2, 3, 4, 5], dtype=torch.int16)

In [32]:
tensor.long()

tensor([0, 1, 2, 3, 4, 5])

In [35]:
tensor.float()

tensor([0., 1., 2., 3., 4., 5.])

In [36]:
tensor.double()

tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)

In [38]:
np_array = np.zeros((5,5))

In [39]:
np_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [55]:
x = torch.tensor([1,2,3])
y= torch.tensor([9,8,7])

In [56]:
x+y

tensor([10, 10, 10])

In [42]:
z = torch.empty(3)

In [43]:
torch.add(x,y,out=z)

tensor([10., 10., 10.])

In [44]:
z = torch.add(x,y)

In [45]:
z2 = x-y

In [46]:
z2

tensor([-8, -6, -4])

In [53]:
z3 = torch.true_divide(x,y)

In [54]:
z3

tensor([0.1111, 0.2222, 0.3333])

In [57]:
t = torch.zeros(3)
t.add_(x)
t

tensor([1., 2., 3.])

In [58]:
t+=x

In [59]:
t

tensor([2., 4., 6.])

In [60]:
z = x.pow(2)
z

tensor([1, 4, 9])

In [61]:
z = x**2

In [62]:
z

tensor([1, 4, 9])

In [63]:
z = x>0

In [64]:
z

tensor([True, True, True])

In [65]:
x>y

tensor([False, False, False])

In [66]:
y<x

tensor([False, False, False])

In [67]:
y>x

tensor([True, True, True])

In [92]:
x = torch.rand((2))
y = torch.rand((2))

In [75]:
x.mm(y)

tensor([[1.2934, 0.4377, 1.0549],
        [1.1728, 0.5008, 1.0647]])

In [86]:
matrix_ex = torch.tensor([[2,3], [4,5]])
matrix_ex

tensor([[2, 3],
        [4, 5]])

In [87]:
matrix_ex.matrix_power(2)

tensor([[16, 21],
        [28, 37]])

In [90]:
x*y

tensor([[0.1904, 0.5190, 0.2642, 0.4517, 0.3647],
        [0.1966, 0.3321, 0.3272, 0.4276, 0.3614]])

In [93]:
torch.dot(x,y)

tensor(0.0704)

In [94]:
batch=32
n=10
m=20
p=30

In [95]:
t1 = torch.rand((batch, n, m))
t2 = torch.rand((batch, m, p))


In [96]:
o1 = torch.bmm(t1, t2)
o1

tensor([[[5.0578, 4.7713, 3.9898,  ..., 6.4475, 5.9040, 4.6910],
         [5.6897, 5.4694, 4.7634,  ..., 7.9159, 6.8253, 5.4745],
         [4.1715, 5.4804, 3.9372,  ..., 6.2521, 5.4755, 4.9232],
         ...,
         [4.8960, 5.2147, 4.6215,  ..., 6.3886, 5.2772, 5.1774],
         [3.0790, 4.0631, 3.0843,  ..., 4.9050, 4.8819, 3.8140],
         [4.9327, 5.6673, 3.9787,  ..., 6.4014, 5.5300, 4.9361]],

        [[5.7046, 5.3456, 5.1660,  ..., 5.5344, 6.2070, 5.5643],
         [6.1588, 4.7930, 4.9751,  ..., 5.0140, 5.1106, 4.6747],
         [4.6228, 4.4489, 3.9343,  ..., 4.9556, 4.9892, 4.1043],
         ...,
         [5.5508, 5.0570, 3.7761,  ..., 5.5872, 5.8870, 5.6158],
         [5.6837, 4.7590, 4.3818,  ..., 3.4284, 5.5562, 4.2822],
         [5.9740, 5.6438, 4.8652,  ..., 5.2545, 6.4185, 5.5633]],

        [[5.2623, 4.8393, 4.6573,  ..., 3.8713, 5.2645, 3.8800],
         [6.1493, 5.7460, 4.8880,  ..., 4.3019, 5.2248, 4.4243],
         [4.8864, 4.1283, 3.9579,  ..., 3.8974, 4.7833, 4.

In [98]:
o1.shape

torch.Size([32, 10, 30])

In [107]:
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))

In [108]:
x1

tensor([[0.2229, 0.6529, 0.5355, 0.9452, 0.7842],
        [0.8820, 0.2332, 0.1465, 0.6135, 0.2951],
        [0.0309, 0.0367, 0.2281, 0.0246, 0.1313],
        [0.1206, 0.8389, 0.5717, 0.0977, 0.3515],
        [0.7000, 0.6434, 0.1339, 0.3369, 0.9974]])

In [109]:
x2

tensor([[0.1486, 0.4059, 0.1029, 0.8261, 0.4797]])

In [110]:
x1-x2

tensor([[ 0.0743,  0.2471,  0.4326,  0.1191,  0.3045],
        [ 0.7334, -0.1727,  0.0436, -0.2126, -0.1846],
        [-0.1177, -0.3691,  0.1252, -0.8015, -0.3484],
        [-0.0280,  0.4331,  0.4687, -0.7284, -0.1282],
        [ 0.5514,  0.2376,  0.0309, -0.4892,  0.5177]])

In [111]:
x1**x2

tensor([[0.8001, 0.8411, 0.9377, 0.9545, 0.8899],
        [0.9815, 0.5538, 0.8206, 0.6679, 0.5569],
        [0.5964, 0.2616, 0.8589, 0.0469, 0.3776],
        [0.7303, 0.9312, 0.9441, 0.1464, 0.6056],
        [0.9484, 0.8361, 0.8130, 0.4071, 0.9988]])

In [112]:
sum_x = torch.sum(x1, dim=0)
sum_x

tensor([1.9565, 2.4053, 1.6157, 2.0179, 2.5596])

In [114]:
values, indices = torch.max(x1, dim=0)
values, indices

(tensor([0.8820, 0.8389, 0.5717, 0.9452, 0.9974]), tensor([1, 3, 3, 0, 4]))

In [115]:
torch.argmax(x1, dim=0)

tensor([1, 3, 3, 0, 4])

In [116]:
torch.mean(x1.float(), dim=0)

tensor([0.3913, 0.4811, 0.3231, 0.4036, 0.5119])

In [117]:
torch.eq(x,y)

tensor([False, False])

In [118]:
torch.sort(y, dim=0, descending=False)

torch.return_types.sort(
values=tensor([0.0571, 0.6625]),
indices=tensor([0, 1]))

In [128]:
torch.clamp_(x1, min=0, max=0.5)

tensor([[0.2229, 0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.2332, 0.2000, 0.5000, 0.2951],
        [0.2000, 0.2000, 0.2281, 0.2000, 0.2000],
        [0.2000, 0.5000, 0.5000, 0.2000, 0.3515],
        [0.5000, 0.5000, 0.2000, 0.3369, 0.5000]])

In [129]:
x2=torch.zeros((2,2))
x2

tensor([[0., 0.],
        [0., 0.]])

In [132]:
torch.any(x2)

tensor(False)

In [133]:
torch.all(x2)

tensor(False)

In [134]:
batch_size = 10
features = 25
x=torch.rand((batch_size, features))

In [139]:
x[:,0].shape

torch.Size([10])

In [140]:
x[2, :10]

tensor([0.5250, 0.8366, 0.3419, 0.2309, 0.6769, 0.3544, 0.5572, 0.3148, 0.2504,
        0.3704])

In [144]:
x = torch.arange(10)+2

In [145]:
indices = [2,5,7]
x[indices]

tensor([4, 7, 9])

In [146]:
x=torch.rand((3,5))
x

tensor([[0.6444, 0.4086, 0.9662, 0.0796, 0.2347],
        [0.2080, 0.3339, 0.9458, 0.2270, 0.9941],
        [0.3833, 0.1432, 0.7052, 0.7708, 0.7196]])

In [147]:
row = torch.tensor([1,0])
col = torch.tensor([4,0])
x[row,col]

tensor([0.9941, 0.6444])

In [150]:
x=torch.arange(10)
x[(x<2)&(x>0)]

tensor([1])

In [151]:
x[x.remainder(2)==0]

tensor([0, 2, 4, 6, 8])

In [152]:
torch.where(x>5, x, x*2)

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])

In [153]:
x.unique()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
x2.ndimension()

2

In [159]:
x=torch.rand((5,5,5))
x.ndimension()


3

In [160]:
x.numel()

125

In [161]:
x = torch.arange(9)
# x.reshape()
x.view(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [162]:
x.reshape(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [174]:
x1 = torch.tensor([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])
x2 = torch.tensor([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])+0.1
x3 = torch.tensor([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])+0.2
# x2 = torch.tensor([[1.1,2.1,3.1],[4.1,5.1,6.1], [7.1,8.1,9.1]])
# x3= torch.tensor([[1.2,2.2,3.2],[4.2,5.2,6.2], [7.2,8.2,9.2]])
z=torch.cat((x1,x2,x3), dim=2)
z

tensor([[[1.0000, 2.0000, 3.0000, 1.1000, 2.1000, 3.1000, 1.2000, 2.2000,
          3.2000],
         [4.0000, 5.0000, 6.0000, 4.1000, 5.1000, 6.1000, 4.2000, 5.2000,
          6.2000]],

        [[1.0000, 2.0000, 3.0000, 1.1000, 2.1000, 3.1000, 1.2000, 2.2000,
          3.2000],
         [4.0000, 5.0000, 6.0000, 4.1000, 5.1000, 6.1000, 4.2000, 5.2000,
          6.2000]]])

In [175]:
batch

32

In [178]:
z=torch.rand(batch, 2,5)
z.view(batch,-1).shape

torch.Size([32, 10])

In [179]:
z1 = z.permute(0,2, 1)

In [180]:
z1.shape

torch.Size([32, 5, 2])

In [191]:
x=torch.arange(10).unsqueeze(1).unsqueeze(0)
x

tensor([[[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]])

In [184]:
x.unsqueeze(1).shape

torch.Size([10, 1])

In [193]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader
import torchvision.datasets as datasets
import torchvision.transforms as transforms

In [ ]:
class NN(nn.Module):
    def __init__(self, input_size, num_classes):
        super(NN, self).__init__()
        self.fc1 = nn.Linear(input_size, 50)
        self.fc2 = nn.Linear(50, num_classes)
        
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x
    
model = NN(784, 10)

